### PR TITLE
Fix issue with callback marshalling

### PR DESCRIPTION
**Pull request by MotorHeat**
Callback lifetime should be the same as WebView main object.

### CODE REVIEW

**Comment by iwillspeak** [comment]
Does this change still guarantee that the callback is not moved by the GC for the lifetime of the window? How does this change the lifetime of the object? Previously it would be kept alive by the GCHandle right?

**Comment by gabrielfreire** [comment]
I'm having a very annoying problem, can't run any of the examples and i think this PR fixes it
Tried _Console app_ and _AspNetCore host app_
```
Exception thrown: 'System.Exception' in Webview.Core.dll
An unhandled exception of type 'System.Exception' occurred in Webview.Core.dll
Could not allocate webview
```

**Comment by MotorHeat** [comment]
Yes that change guarantee that callback will not be collected by GC. Actually lifetime of the callback is the same as lifetime of the "Webview" instance. Callback instance is cretaed in theheap and reference to it is saved in the object.

I was trying original version with .net core and it never works - no callbacks was called on  windows and linux. I don't try Mono or .NET Framework.

Actually calling "GCHandle.Alloc" on object that is allocated on stack it always not good idea.

**Comment by iwillspeak** [comment]
> Actually calling "GCHandle.Alloc" on object that is allocated on stack it always not good idea.

The invoke callback is always heap allocated. It's a reference type not a value type. Both of the following lines would be equivalent:

```csharp

> Yes that change guarantee that callback will not be collected by GC. Actually lifetime of the callback is the same as lifetime of the "Webview" instance. Callback instance is created in the heap and reference to it is saved in the object.

From what I can see the change shouldn't affect the GC lifetime of the callback delegate. It should be referenced either through the `GCHandle` we store inn a field or via the direct field reference in your change. What _does_ change is that without the `GCHandle` how can we be sure the delegate isn't moved in memory by the GC? If that happens then the address we took of it and passed to `webview_alloc` won't be valid any more.

**Comment by iwillspeak** [comment]
Apologies if I'm missing something here. I just know that _without_ the GCHandle to pin the object I _did_ see problems when the delegate got moved by the GC.

**Comment by iwillspeak** [comment]
I wonder if the actual issue here is that the GCHandle isn't pinned?

**Pull request merged**
